### ISSUE TITLE
Disable Ctrl+PageUp/PageDown shortcuts.

### ISSUE THREAD

**Issue by hardhub** [cyd01/KiTTY#230]
It is very annoying when KiTTY overlaps shortcuts from midnight commander.

Is it possible to solve?

**Comment by cyd01** [comment]
To remove shorcuts add these lines to your %APPDATA%/KiTTY/kitty.ini file

    [KiTTY]
    shortcuts=no

**Comment by hardhub** [comment]
@cyd01 

shortcuts=no
mouseshortcuts=no
hyperlink=no

It is already there.. and it does not help.  
I have downloaded newest build and it still does not work.  
I think it is closed too early.

![image](https://user-images.githubusercontent.com/4306334/93689575-92250100-fad8-11ea-8be4-1a7de0b23021.png)

**Comment by hardhub** [comment]
@cyd01 Can you reopen this issue?

**Comment by cyd01** [comment]
Done

**Comment by cyd01** [comment]
Just a question : is it the same with Putty ?

**Comment by hardhub** [comment]
> Just a question : is it the same with Putty ?

Yes, Putty also scrolls.

**Comment by cyd01** [comment]
Issue closed due to inactivity

**Comment by hardhub** [comment]
> Issue closed due to inactivity

Which activity do you expect?  
Bug is still present in both programs.

**Comment by HarryBleckert** [comment]
I do have the same problem when opening a shell from Midnight commander.
Also I can't select text with left muse button anymore after using Midnight Commander.
Only Reset terminal seems to solve that problem!

These problems did not occur using kitty 0.74
